### ISSUE TITLE
upload fails on zip with no models

### ISSUE THREAD

**Issue by meetar** [polygon-city/building-database#89]
Example file: https://github.com/polygon-city/building-database/blob/models/test/models/eiffeltower.zip

```
/Users/peter/work/building-database/controllers/building.js:399
        throw err;
              ^
Error: No model files to process
    at async.waterfall.convertQueue (/Users/peter/work/building-database/controllers/building.js:137:14)
    at fn (/Users/peter/work/building-database/node_modules/async/lib/async.js:641:34)
    at Object._onImmediate (/Users/peter/work/building-database/node_modules/async/lib/async.js:557:34)
    at processImmediate [as _immediateCallback] (timers.js:336:15)
```

**Comment by robhawkes** [comment]
c70238f is a step in the direction of notifying the user of these errors instead of crashing the app (I was perhaps a bit overzealous with my previous error improvements. As things stand, the app won't crash throughout the `/add` process unless there's an unexpected error. For everything else an error message will be returned to the user and displayed on the page. Those messages could do with refining.

**Comment by robhawkes** [comment]
If we're happy with the current fix than I'll close this as we can track any other issues related to errors in #56 or their own tickets.
